# Generated by Django 5.1.7 on 2025-03-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subject_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='category',
            field=models.CharField(choices=[('sayisal', 'Sayısal'), ('esit_agirlik', 'Eşit Ağırlık'), ('sozel', 'Sözel'), ('yabanci_dil', 'Yabancı Dil'), ('tyt', 'TYT')], max_length=12, verbose_name='Alan adı'),
        ),
    ]
